import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed': '#40000c',
        'surface-tint': '#c9c6c5',
        'secondary-container': '#cc003c',
        'surface-dim': '#131313',
        'inverse-on-surface': '#303030',
        'on-tertiary-fixed': '#1a1c1c',
        'tertiary-fixed-dim': '#c6c6c6',
        surface: '#131313',
        'primary-fixed-dim': '#c9c6c5',
        'inverse-primary': '#5f5e5e',
        'surface-container-highest': '#353535',
        tertiary: '#c6c6c6',
        'on-tertiary': '#2f3131',
        'on-primary-fixed': '#1c1b1b',
        'on-primary': '#313030',
        'on-secondary-container': '#ffdcdc',
        'primary-fixed': '#e5e2e1',
        'surface-container-high': '#2a2a2a',
        'on-tertiary-fixed-variant': '#454747',
        'surface-bright': '#393939',
        'error-container': '#93000a',
        'tertiary-fixed': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#1b1c1c',
        'on-background': '#e4e2e1',
        'surface-container': '#1f2020',
        primary: '#c9c6c5',
        'tertiary-container': '#080a0a',
        background: '#131313',
        'on-secondary': '#68001a',
        'on-primary-container': '#7b7979',
        'primary-container': '#0a0a0a',
        'outline-variant': '#444748',
        'on-primary-fixed-variant': '#474646',
        'secondary-fixed-dim': '#ffb3b6',
        'on-secondary-fixed-variant': '#920028',
        error: '#ffb4ab',
        secondary: '#ffb3b6',
        'surface-variant': '#353535',
        'on-error': '#690005',
        'on-surface-variant': '#c4c7c7',
        'on-surface': '#e4e2e1',
        'inverse-surface': '#e4e2e1',
        'on-tertiary-container': '#78797a',
        'secondary-fixed': '#ffdada',
        'surface-container-lowest': '#0e0e0e',
        outline: '#8e9192',
        accent: '#E11D48',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'section-gap': '48px',
        unit: '4px',
        'container-padding': '24px',
        gutter: '16px',
      },
      fontFamily: {
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        'label-caps': ['Geist', 'sans-serif'],
        'label-mono': ['Geist', 'sans-serif'],
        'headline-sm': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.1', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'label-mono': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};

export default config;
